const actionTypes={
    LOAD_COURSE_SUCCESS:'LOAD_COURSE_SUCCESS',
    LOAD_AUTHOR_SUCCESS:'LOAD_AUTHOR_SUCCESS',
    SAVE_COURSE_SUCCESS:'SAVE_COURSE_SUCCESS',
    UPDATE_COURSE_SUCCESS:'UPDATE_COURSE_SUCCESS',
    DELETE_COURSE_SUCCESS:'DELETE_COURSE_SUCCESS',
    CHANGE_COURSE_ACTIVE_STATUS:'CHANGE_COURSE_ACTIVE_STATUS'


};
export default actionTypes;